import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'



export const Layout = ({ children }) => {

    return (
        <>
            <Head>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"/>
            <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-gray-200 min-h-screen">
                <div className="flex min-h-screen">

                    <Navbar></Navbar>


                    <main className="sm:w-2/3 xl:w-4/5 sm:min-h-screen p-3"> 

                        { children }

                    </main>

                </div>
            </div>

        </>
    )
}
